-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    col = {
      active_border = "rgb(7f680b)",
      inactive_border = "rgb(120f02)",
    },
    border_size = 2,
    gaps_in = 3,
    gaps_out = 3,
  },
  group = {
    col = {
      border_active = "rgba(7f680bee)",
      border_inactive = "rgb(120f02)",
    },
    groupbar = {
      col = {
        active = "rgba(ebdbb299)",
        inactive = "rgba(4D574E88)",
      },
      text_color = "rgb(0D0D0D)",
      text_color_inactive = "rgba(D35F5Fff)",
    },
  },
  decoration = {
    rounding = 0,
    shadow = {
      enabled = true,
      render_power = 6,
      range = 20,
      color = "rgba(00000052)",
    },
  },
})
