-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
  { "tahayvr/matteblack.nvim", lazy = false, priority = 1000 },
  {
		"LazyVim/LazyVim",
		opts = {
			colorscheme = "matteblack",
		},
	},
}